openapi: 3.0.0
info:
  title: "NBA Stats API"
  description: "An API for retrieving NBA player, team, and match information."
  version: "1.0.0"
servers:
  - url: "https://{host}:{port}/v1"
    variables:
      host:
        default: "api.example.com"
      port:
        default: "443"
        description: "Port number for HTTPS connections"
paths:
  /players:
    get:
      summary: "List all players"
      description: "Retrieves a list of all NBA players."
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Player"

  /players/{id}:
    get:
      summary: "Retrieve a specific player"
      description: "Retrieves information for a specific NBA player by ID."
      parameters:
        - name: "id"
          in: "path"
          description: "The ID of the player to retrieve."
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Player"
        '404':
          description: "Player not found"

  /teams:
    get:
      summary: "List all teams"
      description: "Retrieves a list of all NBA teams."
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Team"

  /teams/{id}:
    get:
      summary: "Retrieve a specific team"
      description: "Retrieves information for a specific NBA team by ID."
      parameters:
        - name: "id"
          in: "path"
          description: "The ID of the team to retrieve."
          required: true
          schema:
            type: "integer"
            format: "int64"
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Team"
        '404':
          description: "Team not found"

  /games:
    get:
      summary: "List today's games"
      description: "Retrieves a list of all NBA games, today is the default date."
      responses:
        '200':
          description: "Successful operation"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Game"

components:
  schemas:
    Player:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        position:
          type: "string"
        team_id:
          type: "integer"
          format: "int64"
    Team:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        city:
          type: "string"
        conference:
          type: "string"
        division:
          type: "string"
    Game:
      type: "object"
      properties:
        id:
          type: "integer
